// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as RescriptExampleGen from "./RescriptExample.gen";

var author = "@KJYoung";

var greetingStr = "Hi! This is " + author;

function displayStr(fruit, msg, loop) {
  for(var i = 1; i <= loop; ++i){
    if (fruit) {
      console.log("Other Fruit");
    } else {
      console.log(String(i) + ": " + msg + " with Apple");
    }
  }
}

displayStr(/* Apple */0, greetingStr, 3);

var roundedValueJS = Curry._1(Math.round, 3.74);

function roundFromTS(prim) {
  return RescriptExampleGen.myRound(prim);
}

var roundedValueTS = RescriptExampleGen.myRound(3.74);

console.log("JavaScript", roundedValueJS);

console.log("TypeScript", roundedValueTS);

var rounded1 = Curry._1(Math.round, 3.5);

var rounded2 = Curry._1(Math.round, 3.5);

var rounded3 = Curry._1(Math.round, 3.5);

console.log(rounded1);

console.log(rounded2);

console.log(rounded3);

var fruitInstance = /* Apple */0;

export {
  author ,
  greetingStr ,
  fruitInstance ,
  displayStr ,
  roundedValueJS ,
  roundFromTS ,
  roundedValueTS ,
  rounded1 ,
  rounded2 ,
  rounded3 ,
}
/*  Not a pure module */
