// Generated by ReScript, PLEASE EDIT WITH CARE


var author = "@KJYoung";

var greetingStr = "Hi! This is " + author;

function displayStr(fruit, msg, loop) {
  for(var i = 1; i <= loop; ++i){
    if (fruit) {
      console.log("Other Fruit");
    } else {
      console.log(String(i) + ": " + msg + " with Apple");
    }
  }
}

displayStr(/* Apple */0, greetingStr, 3);

var fruitInstance = /* Apple */0;

export {
  author ,
  greetingStr ,
  fruitInstance ,
  displayStr ,
}
/*  Not a pure module */

