// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TargetProblemGen from "./TargetProblem.gen";

function funcInt2Int2(prim) {
  return TargetProblemGen.funcInt2Int2(prim);
}

var funcInt2Int2Ret = TargetProblemGen.funcInt2Int2(5);

export {
  funcInt2Int2 ,
  funcInt2Int2Ret ,
}
/* funcInt2Int2Ret Not a pure module */
